name: build-and-cache

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          overprovision-lvm: true

      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v10
        with:
          name: thiagokokada-nix-configs
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch master

      - name: Check if all '.nix' files are formatted correctly
        run: ./Makefile format-check

      - name: Build Nix configs
        run: ./Makefile all-linux
