name: build-and-cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Free disk space
        run: |
          echo "Freeing disk space"

          echo "=== Before ==="
          df -h

          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          sudo rm -rf /usr/local/lib/android
          docker rmi $(docker image ls -aq)

          echo "=== After ==="
          df -h
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: thiagokokada-nix-configs
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix-shell -p nixFlakes --run 'nix build .#nixosConfigurations.miku-nixos.config.system.build.toplevel --experimental-features "nix-command flakes"'
      - run: nix-shell -p nixFlakes --run 'nix build .#nixosConfigurations.mikudayo-nixos.config.system.build.toplevel --experimental-features "nix-command flakes"'
      - run: nix-shell -p nixFlakes --run 'nix build .#home --experimental-features "nix-command flakes"'
