jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v6
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
      - uses: actions/checkout@v3
      - name: Cache /nix/store
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('flake.*') }}
          path: /tmp/nix-cache
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('flake.*') }}
            ${{ runner.os }}-${{ runner.arch }}-
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Import /nix/store cache
        run: |
          if [[ -f "/tmp/nix-cache" ]]; then
            nix-store --import < "/tmp/nix-cache"
          fi
      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch master
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
          name: thiagokokada-nix-configs
      - name: Build NixOS configs
        run: nix build --print-build-logs -o /tmp/nixos_old '.#nixosConfigurations.miku-nixos.config.system.build.toplevel'
      - name: Build Home-Manager configs
        run: nix build --print-build-logs -o /tmp/hm_old '.#homeConfigurations.home-linux.activationPackage'
      - name: Update flake.lock
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          nix flake update --commit-lock-file
      - name: Build Home-Manager configs
        run: |-
          nix build --print-build-logs '.#homeConfigurations.home-linux.activationPackage'
          nix build --print-build-logs '.#homeConfigurations.steamdeck.activationPackage'
      - name: Build Home-Manager configs
        run: nix build --print-build-logs -o /tmp/hm_new '.#homeConfigurations.home-linux.activationPackage'
      - name: Build NixOS configs
        run: |-
          nix build --print-build-logs '.#nixosConfigurations.miku-nixos.config.system.build.toplevel'
          nix build --print-build-logs '.#nixosConfigurations.mikudayo-re-nixos.config.system.build.toplevel'
          nix build --print-build-logs '.#nixosConfigurations.mirai-vps.config.system.build.toplevel'
      - name: Build NixOS configs
        run: nix build --print-build-logs -o /tmp/nixos_new '.#nixosConfigurations.miku-nixos.config.system.build.toplevel'
      - id: NixOS
        name: 'Diff Nix outputs: /tmp/nixos_old vs /tmp/nixos_new'
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            nix run github:NixOS/nixpkgs/nixos-unstable#nvd -- --color never diff '/tmp/nixos_old' '/tmp/nixos_new'
      - id: Home-Manager
        name: 'Diff Nix outputs: /tmp/hm_old vs /tmp/hm_new'
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            nix run github:NixOS/nixpkgs/nixos-unstable#nvd -- --color never diff '/tmp/hm_old' '/tmp/hm_new'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          body: |
            ## Run report

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ## Changes for NixOS

            ```bash
            ${{ steps.NixOS.outputs.stdout }}
            ```


            ## Changes for Home-Manager

            ```bash
            ${{ steps.Home-Manager.outputs.stdout }}
            ```
          branch: flake-updates
          delete-branch: true
          title: Update flake.lock
      - name: Export /nix/store cache
        run: |
          rm -f "/tmp/"*"-old" "/tmp/nix-cache"
          nix-collect-garbage -d
          nix-store --export $(find "/nix/store" -maxdepth 1 -name '*-*') > "/tmp/nix-cache"
name: update-flakes
"on":
  schedule:
    - cron: 40 4 * * 0,2,4,6
  workflow_dispatch: null
